// flow-typed signature: cf586480e0ba9c02b7424e3278b89b5b
// flow-typed version: <<STUB>>/koa-pug_v^3.0.0-1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-pug'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-pug' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-pug/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'koa-pug/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'koa-pug/src/load-helpers' {
  declare module.exports: any;
}

declare module 'koa-pug/src/pug' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-pug/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'koa-pug/coverage/lcov-report/prettify'>;
}
declare module 'koa-pug/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'koa-pug/coverage/lcov-report/sorter'>;
}
declare module 'koa-pug/index' {
  declare module.exports: $Exports<'koa-pug'>;
}
declare module 'koa-pug/index.js' {
  declare module.exports: $Exports<'koa-pug'>;
}
declare module 'koa-pug/src/load-helpers.js' {
  declare module.exports: $Exports<'koa-pug/src/load-helpers'>;
}
declare module 'koa-pug/src/pug.js' {
  declare module.exports: $Exports<'koa-pug/src/pug'>;
}
