// flow-typed signature: bdfb813d6acb556d47836a610a9e490f
// flow-typed version: <<STUB>>/postcss-normalize_v^0.3.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-normalize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-normalize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-normalize/index' {
  declare module.exports: $Exports<'postcss-normalize'>;
}
declare module 'postcss-normalize/index.js' {
  declare module.exports: $Exports<'postcss-normalize'>;
}
